### ISSUE TITLE
Scheduling Dosing Pump based on Date/Time

### ISSUE THREAD

**Issue by isnuryusuf** [gabrielfc/DosingPumpController#1]
Hi, thanks for sharing your source code, iam wondering  did i miss something on your code related to scheduling dosing pump
can you help to pin out which line on your code to scheduling dosing pump please?

**Comment by gabrielfc** [comment]
Hi, In current version, I only dose in specific hour. View the function checkRelayStatus(), for every loop I call it. Example, for the Pump 1 I always dosing at 6 am if exists some setup defined and so on.

**Comment by isnuryusuf** [comment]
Thanks for your kind response, Wishing You Good Health & Happiness
